app/controllers/AuthController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\NotFoundHttpException;
use yii\web\Response;
use yii\filters\VerbFilter;
use app\forms\LoginForm;
use app\forms\PasswordRequestForm;
use app\forms\PasswordUpdateForm;
use app\forms\RegisterForm;
use app\models\User;

class AuthController extends Controller
{
	/**
	 * @inheritdoc
	 */
	public function behaviors()
	{
		return [
			'access' => [
				'class' => AccessControl::class,
				'only'  => ['logout'],
				'rules' => [
					[
						'actions' => ['logout'],
						'allow'   => true,
						'roles'   => ['@'],
					],
				],
			],
			'verbs'  => [
				'class'   => VerbFilter::class,
				'actions' => [
					'logout' => ['post'],
				],
			],
		];
	}

	/**
	 * Login action.
	 *
	 * @return Response|string
	 */
	public function actionLogin()
	{
		if (! Yii::$app->user->isGuest) {
			return $this->goHome();
		}

		$model = new LoginForm();
		if ($model->load(Yii::$app->request->post()) && $model->login()) {
			$model->assignAuthenticatedRole();
			return $this->goBack();
		}

		return $this->render('login', [
			'model' => $model,
		]);
	}

	/**
	 * Logout action.
	 *
	 * @return Response
	 */
	public function actionLogout()
	{
		Yii::$app->user->logout();

		return $this->goHome();
	}

	/**
	 * Register action.
	 *
	 * @return string|Response
	 */
	public function actionRegister()
	{
		if (!Yii::$app->user->isGuest) {
			return $this->goHome();
		}

		$model = new RegisterForm();

		if ($model->load(Yii::$app->request->post()) && $model->register()) {
			Yii::$app->session->addFlash('success', 'You have been successfully registered');

			return $this->goBack();
		}

		return $this->render('register', [
			'model' => $model,
		]);
	}

	/**
	 * Password request action
	 *
	 * @return string|Response
	 */
	public function actionPasswordRequest()
	{
		if (!Yii::$app->user->isGuest) {
			return $this->goHome();
		}

		$model = new PasswordRequestForm();

		if ($model->load(Yii::$app->request->post()) && $model->request()) {
			Yii::$app->session->addFlash(
				'success',
				'If the email address is registered in the system, we would send a letter there shortly.'
			);

			return $this->goBack();
		}

		return $this->render('password-request', [
			'model' => $model,
		]);
	}

	/**
	 * Password update action
	 *
	 * @param string $token Password reset token.
	 *
	 * @return string|Response
	 * @throws NotFoundHttpException If token not found in DB.
	 */
	public function actionPasswordUpdate($token)
	{
		if (!Yii::$app->user->isGuest) {
			return $this->goHome();
		}

		if (!User::isPasswordResetTokenValid($token)) {
			throw new NotFoundHttpException('Page not found.');
		}

		$model = new PasswordUpdateForm();
		$model->resetToken = $token;

		if ($model->load(Yii::$app->request->post()) && $model->update()) {
			Yii::$app->session->addFlash('success', 'Your password has been successfully updated!');

			return $this->goBack();
		}

		return $this->render('password-update', [
			'model' => $model,
		]);
	}

}

app/views/partials/footer.php
<?php

/* @var $this \yii\web\View */

use yii\helpers\Html;

?>
<footer class="footer">
	<div class="container">
		<p class="pull-left">&copy; My Company <?= date('Y') ?></p>

		<p class="pull-right"><?= Yii::powered() ?></p>
	</div>
</footer>

app/views/partials/header.php
<?php

/* @var $this \yii\web\View */

use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use justcoded\yii2\rbac\models\Item as RbacItem;

NavBar::begin([
	'brandLabel' => 'My Company',
	'brandUrl'   => Yii::$app->homeUrl,
	'options'    => [
		'class' => 'navbar-inverse navbar-fixed-top',
	],
]);
echo Nav::widget([
	'options' => ['class' => 'navbar-nav navbar-right'],
	'items'   => [
        ['label' => 'Products', 'url' => ['/products'], 'visible' => user()->can(RbacItem::PERMISSION_ADMINISTER)],
        ['label' => 'Categories', 'url' => ['/categories'], 'visible' => user()->can(RbacItem::PERMISSION_ADMINISTER)],
        ['label' => 'Discounts', 'url' => ['/discounts'], 'visible' => user()->can(RbacItem::PERMISSION_ADMINISTER)],


        ['label' => 'Home', 'url' => ['/site/index']],
		['label' => 'About', 'url' => ['/site/about']],
		['label' => 'Contact', 'url' => ['/site/contact']],

		['label' => 'Admin Panel', 'url' => ['/admin'], 'visible' => user()->can(RbacItem::PERMISSION_ADMINISTER)],
		Yii::$app->user->isGuest ? (
		['label' => 'Login', 'url' => ['/auth/login']]
		) : (
			'<li>'
			. Html::beginForm(['/auth/logout'], 'post')
			. Html::submitButton(
				'Logout (' . Yii::$app->user->identity->username . ')',
				['class' => 'btn btn-link logout']
			)
			. Html::endForm()
			. '</li>'
		)
	],
]);
NavBar::end();