app/models/Product.php
<?php

namespace app\models;

use Yii;
use yii\helpers\FileHelper;
use yii\web\UploadedFile;

/**
 * This is the model class for table "product".
 *
 * @property int $id
 * @property string $name
 * @property int $quantity
 * @property int $discount
 *
 * @property Image[] $images
 * @property ProductCategory[] $productCategories
 * @property Discount[] $discounts
 */
class Product extends \yii\db\ActiveRecord
{
    /**
     * @var array $images
     */
    public $images;

    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'product';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['name', 'quantity'], 'required'],
            [['name'], 'string', 'max' => 255],
            [['name'], 'unique'],
            ['quantity', 'integer', 'min' => 0],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id'   => 'ID',
            'name' => 'Name',
            'quantity' => 'Quantity',
            'discount' => 'Discount',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getImages()
    {
        return $this->hasMany(Image::class, ['product_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getProductCategories()
    {
        return $this->hasMany(ProductCategory::class, ['product_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getDiscounts()
    {
        return $this->hasMany(Discount::class, ['product_id' => 'id']);
    }


    public function beforeSave($insert)
    {
        if ($this->oldAttributes['quantity'] != $this->attributes['quantity']) {
            $discount = Discount::find()
                ->where('product_id =:pid', [':pid' => $this->id])
                ->andWhere('quantity >=:qua', [':qua' => $this->attributes['quantity']])
                ->orderBy('quantity ASC')
                ->one();
            if ($discount) {
                $this->discount = $discount->discount;
            }
        }
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }


    public function afterSave($insert, $changedAttributes)
    {
        if ($files = UploadedFile::getInstances($this, 'images')) {
            $dir = Yii::getAlias('@productImages') . "$this->id/";
            if (!is_dir($dir)) {
                FileHelper::createDirectory($dir);
            }
            $data = null;
            foreach ($files as $file) {
                $image = time() . '_' . Yii::$app->getSecurity()->generateRandomString(6) . '.' . $file->extension;
                if ($file->saveAs($dir.$image)) {
                    $img = new Image();
                    $img->product_id = $this->id;
                    $img->name = $image;
                    $img->save();
                }
            }
        }
        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
    }

    public function afterDelete()
    {
        $dir = Yii::getAlias('@productImages') . "$this->id";
        if (is_dir($dir)) {
            FileHelper::removeDirectory($dir);
        }

        parent::afterDelete(); // TODO: Change the autogenerated stub
    }
}

app/controllers/DiscountsController.php
<?php

namespace app\controllers;

use app\models\Model;
use app\models\ProductCategory;
use app\models\search\ProductSearch;
use Yii;
use app\models\Discount;
use app\models\Product;
use app\controllers\Controller;
use yii\helpers\ArrayHelper;
use yii\web\NotFoundHttpException;
use yii\web\Response;
use yii\widgets\ActiveForm;

/**
 * DiscountsController implements the CRUD actions for Discount model.
 */
class DiscountsController extends Controller
{
    /**
     * Lists all Discount models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new ProductSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Updates an existing Discount model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = Product::findOne($id);
        $modelProductDiscounts = $model->discounts;

        if (Yii::$app->request->post()) {
            $oldIDs = ArrayHelper::map($modelProductDiscounts, 'id', 'id');

            $modelProductDiscounts = Model::createMultiple(Discount::class, $modelProductDiscounts);
            Model::loadMultiple($modelProductDiscounts, Yii::$app->request->post());

            $deletedIDs = array_diff($oldIDs, array_filter(ArrayHelper::map($modelProductDiscounts, 'id', 'id')));

            foreach ($modelProductDiscounts as $modelProductDiscount) {
                if (!$modelProductDiscount->quantity && !$modelProductDiscount->discount) {
                    $deletedIDs[] = $modelProductDiscount->id;
                }
            }
            // ajax validation
            if (Yii::$app->request->isAjax) {
                Yii::$app->response->format = Response::FORMAT_JSON;
                return ArrayHelper::merge(
                    ActiveForm::validateMultiple($modelProductDiscounts),
                    ActiveForm::validate($model)
                );
            }

            // validate all models
            $valid = Model::validateMultiple($modelProductDiscounts);

            if ($valid) {
                $transaction = \Yii::$app->db->beginTransaction();
                try {
                    if ($flag = $model->save(false)) {
                        if (! empty($deletedIDs)) {
                            Discount::deleteAll(['id' => $deletedIDs]);
                        }
                        if ($modelProductDiscounts) {
                            foreach ($modelProductDiscounts as $modelProductDiscount) {
                                $modelProductDiscount->product_id = $model->id;
                                if (!($flag = $modelProductDiscount->save())) {
                                    $transaction->rollBack();
                                    break;
                                }
                            }
                        }
                    }
                    if ($flag) {
                        $transaction->commit();
                        return $this->redirect(['products/view', 'id' => $model->id]);
                    }
                } catch (\Exception $e) {
                    $transaction->rollBack();
                }
            }
        }

        return $this->render('update', [
            'model' => $model,
            'modelProductDiscounts' => empty($modelProductDiscounts) ? [new Discount] : $modelProductDiscounts,
        ]);
    }
}

app/controllers/ProductsController.php
<?php

namespace app\controllers;

use app\models\Discount;
use app\models\Image;
use app\models\ProductCategory;
use Yii;
use app\models\Product;
use app\models\search\ProductSearch;
use app\models\Model;
use yii\helpers\ArrayHelper;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\Response;
use yii\widgets\ActiveForm;

/**
 * ProductController implements the CRUD actions for Product model.
 */
class ProductsController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::class,
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Product models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new ProductSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Product model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        $model = $this->findModel($id);
        $images = Image::findAll(['product_id' => $id]);
        return $this->render('view', [
            'model' => $model,
            'images' => $images,
        ]);
    }

    /**
     * Creates a new Product model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Product();
        $modelProductCategories = [new ProductCategory];
        if ($model->load(Yii::$app->request->post())) {

            $productCategories['ProductCategory'] = Yii::$app->request->post('ProductCategory');
            $modelProductCategories = Model::createMultiple(ProductCategory::class);
            Model::loadMultiple($modelProductCategories, Yii::$app->request->post());


            // ajax validation
            if (Yii::$app->request->isAjax) {
                Yii::$app->response->format = Response::FORMAT_JSON;
                return ArrayHelper::merge(
                    ActiveForm::validateMultiple($modelProductCategories),
                    ActiveForm::validate($model)
                );
            }

            // validate all models
            $valid = $model->validate();
            $valid = Model::validateMultiple($modelProductCategories) && $valid;

            if ($valid) {
                $transaction = \Yii::$app->db->beginTransaction();
                try {
                    if ($flag = $model->save(false)) {
                        foreach ($modelProductCategories as $modelProductCategory) {
                            if ($modelProductCategory->category_id) {
                                $modelProductCategory->product_id = $model->id;
                                if (!($flag = $modelProductCategory->save())) {
                                    $transaction->rollBack();
                                    break;
                                }
                            }
                        }
                    }
                    if ($flag) {
                        $transaction->commit();
                        return $this->redirect(['view', 'id' => $model->id]);
                    }
                } catch (\Exception $e) {
                    $transaction->rollBack();
                }
            }
        }

        return $this->render('create', [
            'model' => $model,
            'modelProductCategories' => empty($modelProductCategories) ? [new ProductCategory] : $modelProductCategories,
        ]);
    }

    /**
     * Updates an existing Product model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        $modelProductCategories = $model->productCategories;

        if ($model->load(Yii::$app->request->post())) {

            $oldIDs = ArrayHelper::map($modelProductCategories, 'id', 'id');

            $modelProductCategories = Model::createMultiple(ProductCategory::class, $modelProductCategories);
            Model::loadMultiple($modelProductCategories, Yii::$app->request->post());

            $deletedIDs = array_diff($oldIDs, array_filter(ArrayHelper::map($modelProductCategories, 'id', 'id')));

            foreach ($modelProductCategories as $modelProductCategory) {
                if (!$modelProductCategory->category_id) {
                    $deletedIDs[] = $modelProductCategory->id;
                }
            }

            // ajax validation
            if (Yii::$app->request->isAjax) {
                Yii::$app->response->format = Response::FORMAT_JSON;
                return ArrayHelper::merge(
                    ActiveForm::validateMultiple($modelProductCategories),
                    ActiveForm::validate($model)
                );
            }

            // validate all models
            $valid = $model->validate();
            $valid = Model::validateMultiple($modelProductCategories) && $valid;

            if ($valid) {
                $transaction = \Yii::$app->db->beginTransaction();
                try {
                    if ($flag = $model->save(false)) {
                        if (! empty($deletedIDs)) {
                            ProductCategory::deleteAll(['id' => $deletedIDs]);
                        }
                        foreach ($modelProductCategories as $modelProductCategory) {
                            if ($modelProductCategory->category_id) {
                                $modelProductCategory->product_id = $model->id;
                                if (!($flag = $modelProductCategory->save())) {
                                    $transaction->rollBack();
                                    break;
                                }
                            }
                        }
                    }
                    if ($flag) {
                        $transaction->commit();
                        return $this->redirect(['view', 'id' => $model->id]);
                    }
                } catch (\Exception $e) {
                    $transaction->rollBack();
                }
            }
        }

        return $this->render('update', [
            'model' => $model,
            'modelProductCategories' => empty($modelProductCategories) ? [new ProductCategory] : $modelProductCategories,
        ]);

    }

    /**
     * Deletes an existing Product model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Product model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Product the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Product::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

app/views/products/_form.php
<?php

use app\models\Category;
use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\Product */
/* @var $form yii\widgets\ActiveForm */
/* @var array $modelProductCategories */
?>

<div class="product-form">

    <?php $form = ActiveForm::begin([
        'options' => ['enctype' => 'multipart/form-data'],
        'id' => 'dynamic-form',
    ]); ?>

    <?= $form->field($model, 'name')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'quantity')->input('number', ['maxlength' => true]) ?>

    <?= $form->field($model, 'images[]')->widget(\kartik\file\FileInput::class, [
        'options' => ['multiple' => true, 'accept' => 'image/*'],
        'pluginOptions' => ['previewFileType' => 'image']
    ]); ?>

    <div class="panel panel-default">
        <div class="panel-heading"><h4>Categories</h4></div>
        <div class="panel-body">
            <?php
            /** @var array $modelProductCategories */


            \wbraganca\dynamicform\DynamicFormWidget::begin([
                'widgetContainer' => 'dynamicform_wrapper_category', // required: only alphanumeric characters plus "_" [A-Za-z0-9_]
                'widgetBody' => '.container-items', // required: css class selector
                'widgetItem' => '.item', // required: css class
                'limit' => 999, // the maximum times, an element can be cloned (default 999)
                'min' => 1, // 0 or 1 (default 1)
                'insertButton' => '.add-item', // css class
                'deleteButton' => '.remove-item', // css class
                'model' => $modelProductCategories[0],
                'formId' => 'dynamic-form',
                'formFields' => [
                    'category_id',
                ],
            ]); ?>

            <div class="container-items"><!-- widgetContainer -->
                <?php foreach ($modelProductCategories as $i => $modelProductCategory): ?>
                    <div class="item panel panel-default"><!-- widgetBody -->
                        <div class="panel-heading">
                            <h3 class="panel-title pull-left">Category</h3>
                            <div class="pull-right">
                                <button type="button" class="add-item btn btn-success btn-xs"><i class="glyphicon glyphicon-plus"></i></button>
                                <button type="button" class="remove-item btn btn-danger btn-xs"><i class="glyphicon glyphicon-minus"></i></button>
                            </div>
                            <div class="clearfix"></div>
                        </div>
                        <div class="panel-body">
                            <?php
                            // necessary for update action.
                            if (!$modelProductCategory->isNewRecord) {
                                echo Html::activeHiddenInput($modelProductCategory, "[{$i}]id");
                            } ?>
                            <div class="row">
                                <div class="col-sm-6">
                                    <?= $form->field($modelProductCategory, "[{$i}]category_id")->dropDownList(app\models\Category::getSelectForProduct(), [
                                        'prompt' => 'without category',
                                        'class'  => 'form-control form-field-short',
                                    ]); ?>
                                </div>
                            </div><!-- .row -->
                        </div>
                    </div>
                <?php endforeach; ?>
            </div>
            <?php \wbraganca\dynamicform\DynamicFormWidget::end(); ?>
        </div>
    </div>

    <div class="form-group">
        <?= Html::submitButton('Save', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

<?php
$this->registerJs('
    $(".dynamicform_wrapper_category").on("beforeInsert", function(e, item) {
    console.log("beforeInsert");
});

$(".dynamicform_wrapper_category").on("afterInsert", function(e, item) {
    console.log("afterInsert");
});

$(".dynamicform_wrapper_category").on("beforeDelete", function(e, item) {
    if (! confirm("Are you sure you want to delete this item?")) {
        return false;
    }
    return true;
});

$(".dynamicform_wrapper_category").on("afterDelete", function(e) {
    console.log("Deleted item!");
});

$(".dynamicform_wrapper_category").on("limitReached", function(e, item) {
    alert("Limit reached");
});
')?>

app/views/products/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\search\ProductSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="product-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
        'options' => [
            'data-pjax' => 1
        ],
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'name') ?>

    <?= $form->field($model, 'quantity') ?>

    <?= $form->field($model, 'discount') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

app/views/products/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Product */
/** @var array $modelProductCategories */

$this->title = 'Create Product';
$this->params['breadcrumbs'][] = ['label' => 'Products', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="product-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?=
    $this->render('_form', [
        'model' => $model,
        'modelProductCategories' => $modelProductCategories,
    ]) ?>

</div>

app/views/products/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\widgets\Pjax;
/* @var $this yii\web\View */
/* @var $searchModel app\models\search\ProductSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Products';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="product-index">

    <h1><?= Html::encode($this->title) ?></h1>
    <?php Pjax::begin(); ?>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <p>
        <?= Html::a('Create Product', ['create'], ['class' => 'btn btn-success']) ?>
    </p>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            'id',
            'name',
            'quantity',
            'discount',

            ['class' => 'yii\grid\ActionColumn'],
        ],
    ]); ?>
    <?php Pjax::end(); ?>
</div>

app/views/products/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Product */
/** @var array $modelProductCategories */

$this->title = 'Update Product: ' . $model->name;
$this->params['breadcrumbs'][] = ['label' => 'Products', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->name, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="product-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?=
    $this->render('_form', [
        'model' => $model,
        'modelProductCategories' => $modelProductCategories,
    ]) ?>

</div>

app/views/products/view.php
<?php

use yii\helpers\BaseStringHelper;
use yii\helpers\Html;
use yii\widgets\DetailView;
use app\assets\AssetBundle;

/* @var $this yii\web\View */
/* @var $model app\models\Product */


$assets = AssetBundle::register($this);

$this->title = $model->name;
$this->params['breadcrumbs'][] = ['label' => 'Products', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);
?>
<div class="product-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Update', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'name',
            'quantity',
            [
                'label'     => Html::a(\Yii::t('app', $model->getAttributeLabel('discount')), ['discounts/update', 'id' => $model->id]),
                'attribute' => 'discount',
                'value'     => function ($model) {
                    return $model->discount ? $model->discount : 0;
                }
            ],
        ],
    ]) ?>

<!--    Image block    -->
    <div class="row">
        <?php
            /** @var \app\models\Image $images */
            foreach ($images as $image) {
        ?>
        <div class="col-md-3">
            <div class="card">

                <div class="zoom-gallery">
                    <a href="<?= "$assets->baseUrl/images/products/$model->id/$image->name" ?>" style="width: 100%;">
                        <img id="map" src="<?= "$assets->baseUrl/images/products/$model->id/$image->name" ?>" width="200" height="200">
                    </a>
                    <?= Html::a(
                        \Yii::t('app', 'Delete Image'),
                        ['images/delete', 'id' => $image->id],
                        ['class' => 'btn left-space btn-danger','data' => [
                            'method' => 'post',
                            ],
                        ]
                    ); ?>
                </div>
            </div>
        </div>
        <?php } ?>
    </div>
</div>